### ISSUE TITLE
BUG: Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0...

### ISSUE THREAD

**Issue by deltakegmail** [dmitry-pavlov/openapi-connected-service#29]
Any idea?

Generating code for https://petstore.swagger.io/v2/swagger.json
Error:Adding OpenAPI (Swagger) Connected Service to the project failed: Could not load file or assembly 'Newtonsoft.Json, Version=11.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)

Microsoft Visual Studio Enterprise 2017 
Version 15.9.6
VisualStudio.15.Release/15.9.6+28307.344
Microsoft .NET Framework
Version 4.7.03190

Installed Version: Enterprise

C# Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
C# components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Common Azure Tools   1.10
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

NuGet Package Manager   4.6.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

ProjectServicesPackage Extension   1.0
ProjectServicesPackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

ResourcePackage Extension   1.0
ResourcePackage Visual Studio Extension Detailed Info

Visual Basic Tools   2.10.0-beta2-63501-03+b9fb1610c87cccc8ceb74a770dba261a58e39c4a
Visual Basic components used in the IDE. Depending on your project type and settings, a different version of the compiler may be used.

Visual Studio Code Debug Adapter Host Package   1.0
Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

**Comment by dmitry-pavlov** [comment]
@deltakegmail generated code uses `Newtonsoft.Json` to deserialize JSON response from API you are using. So you just need to add this NuGet package to you project as descibed [here](https://github.com/dmitry-pavlov/openapi-connected-service#generated-code-compilation-errors) to fix this compilation error.

**Comment by jermoe1** [comment]
I actually encountered this same error today, even with the Newtonsoft.Json NuGet package added.

I tried with all of the recent versions available: 10.0.3, 11.0.1, 11.0.2, and 12.0.1


![image](https://user-images.githubusercontent.com/28392966/53246205-063dbf80-367e-11e9-8c98-affc46997025.png)

![image](https://user-images.githubusercontent.com/28392966/53246016-73048a00-367d-11e9-8acc-371e472dcf25.png)

**Comment by dmitry-pavlov** [comment]
Thanks for letting me know @jermoe1! I am re-opening the issue @deltakegmail for investigation. 
Folks, could you please let me know what type of .NET project you both were trying to add API reference? I mean was it Full .NET or .NET Core, web app, or class library? If you don't mind - please send me the .csproj file to me@dmitry-pavlov.com TIA!

**Comment by rellingson516** [comment]
Tried this as well and ran into the same issue. I made a fresh project targeting .NET Core 2.0. I added the latest versions of all the nuget packages you recommended in the troubleshooting guide. 

My .csproj file looks as follows:

<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp2.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Newtonsoft.Json" Version="12.0.1" />
    <PackageReference Include="System.Net.Http" Version="4.3.4" />
    <PackageReference Include="System.Runtime.Serialization.Json" Version="4.3.0" />
  </ItemGroup>

</Project>

**Comment by dmitry-pavlov** [comment]
@rellingson516 thanks for provided details. I will keep you posted here. Stay tuned

**Comment by hiramlight** [comment]
Got the same issue so I stay tuned...

Cheers

Alan

**Comment by labcubedev** [comment]
The same issue persists on .NET Core 2.2.X

**Comment by dmitry-pavlov** [comment]
@labcubedev could you please send me your .csproj file to [me@dmitry-pavlov.com](mailto:me@dmitry-pavlov.com)?

**Comment by dmitry-pavlov** [comment]
I have fixed the bug. You should see a notification about update to `v 1.1.3` for the extension in your Visual Studio - please update (or remove the older version first to make a clean install). 

Please kindly verify and let me know if you still see the issue. Thanks everyone for your feedback!

**Comment by dmitry-pavlov** [comment]
@deltakegmail @jermoe1 @rellingson516 @hiramlight @labcubedev could you please let me know if you had a chance to try version `1.1.3`? Can you confirm the issue has been addressed?

Thanks for helping me with improving the project by providing valuable feedback! Please feel free to add your review here https://marketplace.visualstudio.com/items?itemName=dmitry-pavlov.OpenAPIConnectedService#review-details 

Look forward to hearing from you. Have a great weekend!

**Comment by vikramkhyadi** [comment]
@dmitry-pavlov I am still facing the same issue Could not load file or assembly 'Newtonsoft.Json, Version=12.0.0.0, Culture=neutral, PublicKeyToken=30ad4fe6b2a6aeed' in .netcore 3.1. Swagger is working fine in dev environment, but its throwing the above error when its deployed.
